name: WebPImageConverter Build

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    needs: php82

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Checkout to Master Built
      if: github.ref == 'refs/heads/master'
      env:
        USER_EMAIL: "badasswpdev@gmail.com"
        USER_NAME: "badasswp"
      run: |
        git config user.email "${USER_EMAIL}"
        git config user.name "${USER_NAME}"
        git checkout -b master-built

    - name: Build Vendor folder
      run: |
        composer install --no-dev
        git add vendor/ -f
        git rm composer.json

    - name: Clean Up Files
      run: |
        while IFS= read -r file; do
          git rm -r "$file"
        done < .deployignore
        git rm .deployignore
        git clean -f composer.lock

    - name: Push to Master Built
      run: |
        git commit -m "push to master-built"
        git push origin master-built -f
        rm -rf .git
